### ISSUE TITLE
Session Token field is missing in 2.0.10

### ISSUE THREAD

**Issue by kylegibson** [Reggino/SdbNavigator#33]
I'm using 2.0.10 and it seems the Session Token field is missing, despite being implemented in https://github.com/Reggino/SdbNavigator/pull/28. I seem to recall using that feature a few months ago.

**Comment by Reggino** [comment]
Yeah, i've been struggling a bit with the item in the chrome store due to issue #32. I'm afraid i messed up a bit there... 

Just released a new version (2.0.11) with the latest code properly that Google will accept pretty soon. 

If this takes too long, you may want to install the plugin manually. It can be downloaded from https://github.com/Reggino/SdbNavigator/releases/tag/2.0.11 . Just unzip it somewhere and install it as a "custom extension" in your browser.
